import React,{useMemo,useState} from 'react'
import {Link} from 'gatsby'
import {ArrowUpRight,FileText,Search} from 'lucide-react'
import PageLayout from '../components/PageLayout'
import SEO from '../components/SEO'
export default function Proposals({pageContext:{proposals,sources}}){
  const [query,setQuery]=useState(''),[year,setYear]=useState('all'),[outcome,setOutcome]=useState('all')
  const years=[...new Set(proposals.map(p=>p.year))].sort((a,b)=>b-a)
  const filtered=useMemo(()=>proposals.filter(p=>(year==='all'||p.year===Number(year))&&(outcome==='all'||p.outcome===outcome)&&`${p.organizationName} ${p.title}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.year-a.year||a.organizationName.localeCompare(b.organizationName)),[proposals,query,year,outcome])
  return <PageLayout wide><div className="page-eyebrow">Learn from the community</div><h1>A proposal starts with a good idea.</h1><p className="page-intro">Explore public GSoC proposals by organization, year and reported outcome. Use them to understand structure and scope, then write your own.</p>
    <div className="proposal-controls"><label className="proposal-search"><Search size={18} aria-hidden="true"/><input type="search" aria-label="Search proposal examples" placeholder="Search organizations or proposal titles…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Proposal year" value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select aria-label="Reported proposal outcome" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="all">All outcomes</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="unknown">Not recorded</option></select></div>
    <p role="status" className="resource-result-count">{filtered.length} proposal examples</p>
    <div className="proposal-grid">{filtered.map(p=><article className="proposal-card" key={p.id}><div className="proposal-meta"><span>GSoC {p.year}</span><span className={`outcome outcome-${p.outcome}`}>{p.outcome==='unknown'?'Not recorded':p.outcome}</span></div><h2><a href={p.url} target="_blank" rel="noreferrer"><FileText size={16} aria-hidden="true"/>{p.title}<ArrowUpRight size={16} aria-hidden="true"/></a></h2><p>{p.organizationSlug?<Link to={`/organizations/${p.organizationSlug}/`}>{p.organizationName}</Link>:p.organizationName}</p><a className="proposal-source" href={p.sourceUrl} target="_blank" rel="noreferrer">{p.sourceLabel} ↗</a></article>)}</div>
    {!filtered.length&&<div className="empty-state"><h2>No proposals match</h2><button type="button" onClick={()=>{setQuery('');setYear('all');setOutcome('all')}}>Reset proposal filters</button></div>}
    <section className="prose resource-notes"><h2>About these examples</h2><p>Acceptance and rejection labels come from the archive folders or descriptions. We have not independently verified those outcomes. These examples are a small, self-selected sample and cannot measure an organization’s acceptance rate. A proposal link does not establish program participation.</p><p>Documents remain on their authors’ repositories; we index links, not the document contents. Some files include the author’s name in the title. Please respect their work and do not copy a proposal.</p><h3>Browse the full archives</h3><ul>{sources.map(s=><li key={s.repo}><a href={`https://github.com/${s.repo}`}>{s.label}</a></li>)}</ul><p>Missing an example? <a href="https://github.com/satwiksps/openorganizations/issues/new">Suggest a public proposal link</a>.</p></section>
  </PageLayout>
}
export const Head=()=> <SEO title="Open-source proposal examples" description="Browse public GSoC proposal examples by organization, year, and reported outcome, with links to their community archives." path="/proposals/"/>
