import React,{useMemo,useState} from 'react'
import {Link} from 'gatsby'
import {ArrowUpRight,FileText,Search} from 'lucide-react'
import PageLayout from '../components/PageLayout'
import AdSlot from '../components/AdSlot'
import SEO from '../components/SEO'
export default function Proposals({pageContext:{proposals,sources}}){
  const [query,setQuery]=useState(''),[year,setYear]=useState('all'),[outcome,setOutcome]=useState('all'),[program,setProgram]=useState('all'),[limit,setLimit]=useState(30)
  const years=[...new Set(proposals.map(p=>p.year))].sort((a,b)=>b-a)
  const filtered=useMemo(()=>proposals.filter(p=>(program==='all'||p.program===program)&&(year==='all'||p.year===Number(year))&&(outcome==='all'||p.outcome===outcome)&&`${p.organizationName} ${p.title}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.year-a.year||a.organizationName.localeCompare(b.organizationName)),[proposals,query,year,outcome,program])
  return <PageLayout wide><h1>Proposal library</h1><p className="page-intro">Browse public GSoC, LFX and Summer of Bitcoin proposals.</p>
    <div className="proposal-controls"><label className="proposal-search"><Search size={18} aria-hidden="true"/><input type="search" aria-label="Search proposal examples" placeholder="Search organizations or proposal titles…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Proposal program" value={program} onChange={e=>setProgram(e.target.value)}><option value="all">All programs</option><option value="gsoc">GSoC</option><option value="lfx">LFX</option><option value="sob">SoB</option></select><select aria-label="Proposal year" value={year} onChange={e=>setYear(e.target.value)}><option value="all">All years</option>{years.map(y=><option key={y} value={y}>{y}</option>)}</select><select aria-label="Reported proposal outcome" value={outcome} onChange={e=>setOutcome(e.target.value)}><option value="all">All outcomes</option><option value="accepted">Accepted</option><option value="rejected">Rejected</option><option value="unknown">Not recorded</option></select></div>
    <p role="status" className="resource-result-count">{filtered.length} proposal examples</p>
    <div className="proposal-grid">{filtered.slice(0,limit).map((p,i)=><React.Fragment key={p.id}><article className="proposal-card" key={p.id}><div className="proposal-meta"><span>{{gsoc:'GSoC',lfx:'LFX',sob:'SoB'}[p.program]} {p.year}</span><span className={`outcome outcome-${p.outcome}`}>{p.outcome==='unknown'?'Not recorded':p.outcome}</span></div><h2><a href={p.url} target="_blank" rel="noreferrer"><FileText size={16} aria-hidden="true"/>{p.title}<ArrowUpRight size={16} aria-hidden="true"/></a></h2><p>{p.organizationSlug?<Link to={`/organizations/${p.organizationSlug}/`}>{p.organizationName}</Link>:p.organizationName}</p><a className="proposal-source" href={p.sourceUrl} target="_blank" rel="noreferrer">{p.sourceLabel} ↗</a></article>{i===7&&filtered.length>8&&<AdSlot placement="proposals"/>}</React.Fragment>)}</div>{filtered.length>limit&&<button className="show-suborgs" onClick={()=>setLimit(n=>n+30)}>Show {Math.min(30,filtered.length-limit)} more</button>}
    {!filtered.length&&<div className="empty-state"><h2>No proposals match</h2><button type="button" onClick={()=>{setQuery('');setYear('all');setOutcome('all');setProgram('all');setLimit(30)}}>Reset proposal filters</button></div>}
    <section className="prose resource-notes"><h2>About these examples</h2><p>Outcomes come from archive maintainers and are not independently verified. This collection cannot measure acceptance rates.</p><p>Documents remain in their authors’ repositories. Learn from their structure and write your own proposal.</p><h3>Browse the full archives</h3><ul>{sources.map(s=><li key={s.repo}><a href={`https://github.com/${s.repo}`}>{s.label}</a></li>)}</ul><p>Missing an example? <a href="https://github.com/satwiksps/openorganizations/issues/new">Suggest a public proposal link</a>.</p></section>
  </PageLayout>
}
export const Head=()=> <SEO title="Open-source proposal examples" description="Browse public GSoC proposal examples by organization, year, and reported outcome, with links to their community archives." path="/proposals/"/>
