import React from "react"
import { ArrowUpRight } from "lucide-react"
import PageLayout from "../components/PageLayout"
import SEO from "../components/SEO"

export default function SourcesPage({ pageContext: { programs, organizations, generatedAt } }) {
  return <PageLayout wide><div className="page-eyebrow">Transparent by design</div><h1>Know where the data comes from.</h1><p className="page-intro">This is a community-maintained directory. Coverage varies by program; participation history is not a list of currently open applications.</p><div className="source-table-wrap"><table className="source-table"><thead><tr><th>Program</th><th>Coverage</th><th>Organizations</th><th>Source</th></tr></thead><tbody>{programs.map(program => <tr key={program.id}><td>{program.label}<small>{program.name}</small></td><td>{program.coverage}{program.sourceAttribution && <small>{program.sourceAttribution} · {program.sourceLicense}</small>}</td><td>{organizations.filter(org => org.participations.some(p => p.program === program.id)).length}</td><td><a href={program.sourceUrl || program.url} target="_blank" rel="noreferrer">View source <ArrowUpRight size={12} /></a></td></tr>)}</tbody></table></div><p className="source-meta">Dataset assembled: {generatedAt ? new Date(generatedAt).toISOString().slice(0,10) : "See source files"}. Individual participation records retain their own source and verification date.</p>
    <div className="prose"><h2>How records are maintained</h2><p>We combine program publications and attributed community datasets into checked-in snapshots. Automated validation checks program IDs, dates, links, duplicate records and required fields before a snapshot is published. A failed refresh leaves the previous published dataset in place.</p><p>Names and explicit aliases connect the same organization across programs. The directory shows one organization card, while each program, year and cohort remains a separate participation record. Project-level records and umbrella organizations are not automatically merged just because they share a hosting domain.</p><h2>What “applications open” means</h2><p>That filter requires an explicitly recorded open status and a valid, unexpired application deadline. Missing or ambiguous dates are treated as unknown. Always confirm the official timeline before applying.</p><h2>Corrections and missing programs</h2><p>Use the correction link on an organization’s page or <a href="https://github.com/satwiksps/openorganizations/issues/new?template=data-correction.yml">open a data issue</a> with an official source. Additional programs can be added through the program registry and a documented data import.</p><h2>Credits and reuse</h2><p>The project draws on <a href="https://github.com/nishantwrp/gsoc-organizations">GSoC Organizations by Nishant</a> (GPL-3.0) and the <a href="https://github.com/Jaydeep869/SOB_Organizations">Summer of Bitcoin directory by Jaydeep</a> (MIT). Original notices are retained in the source. Program names, organization marks and linked project materials belong to their respective owners.</p><p>Our code is available under GPL-3.0. <a href="https://github.com/satwiksps/openorganizations">Browse the repository</a> or <a href="/source.tar.gz" download>download the corresponding source archive</a>. Source attribution and coverage notes are included with the data.</p></div>
  </PageLayout>
}
export const Head = () => <SEO title="Data sources & coverage" description="See the sources, coverage, verification process and open-source credits behind OpenOrganizations." path="/sources/" />
