import React from "react"
import { Link } from "gatsby"
import PageLayout from "../components/PageLayout"
import SEO from "../components/SEO"

export default function About() {
  return <PageLayout><div className="page-eyebrow">About OpenOrganizations</div><h1>A starting point for your next contribution.</h1><p className="page-intro">Find open-source communities through the programs they participate in, the technologies they use and the problems they work on.</p><div className="prose"><h2>How to use the directory</h2><ol><li>Choose a program, or browse all organizations together.</li><li>Search for your interests and filter by technology, topic or participation year.</li><li>Open an organization to review its program history and project links.</li><li>Read its contribution guide and the official program requirements before applying.</li></ol><h2>Participation is a starting point</h2><p>Organizations change their project ideas and availability between cohorts. Historical participation can help you discover a community, but it does not guarantee future participation, funding or an open application.</p><p>Some programs also include documentation, design and other non-code contributions. Explore the project sources even if a technology filter doesn’t describe your skills.</p><h2>An independent community project</h2><p>OpenOrganizations is maintained by <a href="https://github.com/satwiksps">Satwik</a>. It is not affiliated with or endorsed by the programs listed here. The familiar directory layout is inspired by <a href="https://www.gsocorganizations.dev/">GSoC Organizations</a>; source credits and licensing are documented on our <Link to="/sources/">data and sources page</Link>.</p><h2>Contact and contribute</h2><p>Report an incorrect record, suggest a program or raise a site issue through <a href="https://github.com/satwiksps/openorganizations/issues">GitHub issues</a>. Include a reliable source when suggesting data changes.</p>{process.env.GATSBY_CONTACT_EMAIL && <p>Email: <a href={`mailto:${process.env.GATSBY_CONTACT_EMAIL}`}>{process.env.GATSBY_CONTACT_EMAIL}</a>.</p>}</div></PageLayout>
}
export const Head = () => <SEO title="About" path="/about/" />
