import React from 'react'
import PageLayout from '../components/PageLayout'
import SEO from '../components/SEO'
const endpoints=[['/api/v1/organizations.json','All organizations','meta, organizations'],['/api/v1/programs.json','Program registry and coverage','meta, programs'],['/api/v1/proposals.json','Proposal links and source archives','meta, sources, proposals'],['/api/v1/organizations/3dtk.json','One organization, by slug','meta, organization, proposals']]
export default function Api(){return <PageLayout wide><h1>OpenOrganizations API</h1><p className="page-intro">Public JSON for organizations, programs and proposals. No API key required.</p><div className="source-table-wrap"><table className="source-table"><thead><tr><th>GET endpoint</th><th>Contents</th><th>Response keys</th></tr></thead><tbody>{endpoints.map(([url,label,keys])=><tr key={url}><td><a href={url} target="_blank" rel="noreferrer"><code>{url}</code></a></td><td>{label}</td><td><code>{keys}</code></td></tr>)}</tbody></table></div><section className="prose"><h2>Quick start</h2><pre className="api-example"><code>{`const response = await fetch('https://openorganizations.site/api/v1/organizations.json');
if (!response.ok) throw new Error('API request failed');
const { organizations } = await response.json();
const gsoc = organizations.filter(org =>
  org.participations.some(p => p.program === 'gsoc')
);`}</code></pre><h2>How it works</h2><p>These are static snapshots, updated with website deployments. Filter the response in your code; query parameters do not filter these endpoints. Reuse a downloaded snapshot instead of requesting it for every result. Cross-origin browser requests are supported.</p><p>Each organization includes its slug, description, website, technologies, topics and participation records. Each participation identifies its program, year, cohort, projects and source. Use an organization’s slug in <code>/api/v1/organizations/SLUG.json</code>. Unknown slugs return 404.</p><h2>Coverage and attribution</h2><p>The API uses the same directory cutoff as the website: at least one indexed participation from 2016 onward. Earlier history for retained organizations remains available. Proposal outcomes are reported by archive maintainers. Preserve source URLs, attribution and license fields when reusing data; see <a href="/sources/">sources and coverage</a>.</p></section></PageLayout>}
export const Head=()=> <SEO title="Public JSON API" description="Access OpenOrganizations organization, program and proposal data through a free public JSON API." path="/api/"/>
