import React from "react"
import PageLayout from "../components/PageLayout"
import SEO from "../components/SEO"

export default function Privacy() {
  const adsConfigured = Boolean(process.env.GATSBY_ADSENSE_CLIENT && process.env.GATSBY_ADSENSE_SLOT)
  return <PageLayout><div className="page-eyebrow">Privacy</div><h1>Explore without an account.</h1><div className="prose"><p>OpenOrganizations is a public directory. Search and filtering run in your browser. There is no account system and we do not ask for your name, email address or application information to browse.</p><h2>Searches and links</h2><p>Filters and search terms are stored in the page URL so you can bookmark or share a view. URLs may appear in browser history and hosting access logs. Avoid entering personal or sensitive information into search.</p><h2>Hosting and external resources</h2><p>The hosting provider processes connection information, such as IP addresses and request details, to deliver and protect the site. Organization logos may load from their original hosts, which receive those image requests. Links to program websites, project repositories and GitHub are governed by those services’ privacy policies.</p><h2>Cookies and advertising</h2>{adsConfigured ? <p>Advertising is configured for this site. The advertising integration loads only after the configured consent system signals permission. Ad providers may use cookies or similar technologies to measure and personalize ads according to your choices. Use the consent controls provided by the site to review or withdraw those choices. See <a href="https://policies.google.com/technologies/partner-sites">how Google uses information from partner sites</a>.</p> : <p>Advertising and analytics are currently disabled. The directory does not set advertising cookies or store search preferences in local storage.</p>}<h2>Public contributions</h2><p>Information you submit through a public GitHub issue or pull request is visible according to GitHub’s repository and account settings. Do not include sensitive personal information in public contributions.</p><h2>Contact</h2><p>For privacy questions, contact the maintainer through <a href="https://github.com/satwiksps">their GitHub profile</a>{process.env.GATSBY_CONTACT_EMAIL ? <> or <a href={`mailto:${process.env.GATSBY_CONTACT_EMAIL}`}>{process.env.GATSBY_CONTACT_EMAIL}</a></> : ""}.</p></div></PageLayout>
}
export const Head = () => <SEO title="Privacy" path="/privacy/" />
