import React,{useState} from 'react'
import {Link} from 'gatsby'
export default function SubOrganizations({organization}){
  const [query,setQuery]=useState(''),[sort,setSort]=useState('frequency'),[expanded,setExpanded]=useState(false)
  const children=organization.subOrganizations||[]
  if(!children.length)return null
  const allYears=[...new Set(children.flatMap(c=>c.years))]
  const covered=organization.umbrellaProgram==='lfx'?allYears:[...new Set(organization.participations.filter(p=>p.program==='gsoc').map(p=>p.year))]
  const rows=children.filter(c=>`${c.name} ${(c.aliases||[]).join(' ')}`.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>sort==='name'?a.name.localeCompare(b.name):b.years.length-a.years.length||b.projectCount-a.projectCount||a.name.localeCompare(b.name))
  return <section className="detail-section" id="sub-organizations"><div className="detail-section-title"><h2>Sub-organizations</h2><span>{children.length} indexed</span></div><p className="suborg-explainer">{organization.umbrellaProgram==='lfx'?'Frequency counts distinct years with recorded CNCF LFX projects. Multiple terms in one year count once.':'Counts years with a named project match. Generic titles may be missed; ideas-list years are counted separately.'} <a href={organization.umbrellaSource} target="_blank" rel="noreferrer">Umbrella source ↗</a></p>
    <div className="proposal-controls"><input type="search" aria-label="Search sub-organizations" placeholder="Find a sub-organization…" value={query} onChange={e=>setQuery(e.target.value)}/><select aria-label="Sort sub-organizations" value={sort} onChange={e=>setSort(e.target.value)}><option value="frequency">Most frequent</option><option value="name">Name A–Z</option></select></div><p role="status" className="resource-result-count">{rows.length} communities · {covered.length} indexed {organization.umbrellaProgram==='lfx'?'LFX':'GSoC'} years</p>
    <div className="source-table-wrap"><table className="source-table suborg-table"><thead><tr><th>Community</th><th>Project frequency</th><th>Years</th><th>Evidence</th></tr></thead><tbody>{(expanded || query ? rows : rows.slice(0,12)).map(c=><tr key={c.name}><td>{c.organizationSlug?<Link to={`/organizations/${c.organizationSlug}/`}>{c.name}</Link>:<a href={c.website} target="_blank" rel="noreferrer">{c.name} ↗</a>}{c.communityLinks?.length>0&&<div className="suborg-community-links">{c.communityLinks.map(l=><a key={l.url} href={l.url} target="_blank" rel="noreferrer">{l.label} ↗</a>)}</div>}</td><td><strong>{c.years.length} / {covered.length} years</strong><small>{c.projectCount} indexed projects</small>{c.ideaYears.length>0&&<small>{c.ideaYears.length} ideas-list years (separate)</small>}</td><td>{c.years.length?c.years.join(', '):'No named project match'}</td><td><details><summary>View sources</summary><ul>{c.evidence.map((e,i)=><li key={`${e.url}-${i}`}><a href={e.url} target="_blank" rel="noreferrer">{e.year} · {e.title}</a></li>)}{c.ideaYears.map(e=><li key={`idea-${e.year}`}><a href={e.sourceUrl} target="_blank" rel="noreferrer">{e.year} · Ideas listing</a></li>)}</ul></details></td></tr>)}</tbody></table></div>{rows.length>12&&!query&&<button className="show-suborgs" type="button" onClick={()=>setExpanded(value=>!value)}>{expanded?"Show fewer communities":`Show all ${rows.length} communities`}</button>}{!rows.length&&<p>No matching sub-organizations.</p>}
  </section>
}
